# Generated by Django 3.0.6 on 2020-06-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
