# Generated by Django 3.0.6 on 2020-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_node_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='truth_value',
            field=models.FloatField(default=0.0),
        ),
    ]
