# Generated by Django 3.0.6 on 2020-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_node_truth_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
