# Generated by Django 3.0.6 on 2020-05-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='n_confirmations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edge',
            name='usr_reading',
            field=models.IntegerField(default=0),
        ),
    ]
