# Generated by Django 3.0.6 on 2020-06-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='reliability',
            field=models.FloatField(default=0.0),
        ),
    ]
