# Generated by Django 3.0.6 on 2020-05-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_voter_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='streak',
            field=models.IntegerField(default=1),
        ),
    ]
