# Generated by Django 3.0.6 on 2020-05-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_voter_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='reading_time',
            field=models.FloatField(default=0.0),
        ),
    ]
