# Generated by Django 3.0.6 on 2020-06-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_auto_20200526_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
